### Return all blogs
GET http://localhost:3001/api/blogs

### Return a blog for id
GET http://localhost:3001/api/blogs/:id

### POST: Create a blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndUNhc3RybyIsImlkIjoiNjY2OGE0NmNlNzJlMjBlMTdiNWQxZmNkIiwiaWF0IjoxNzE4MTM5ODU1LCJleHAiOjE3MTgxNDM0NTV9.0zkI6DPkQgsUOzwYTNi0Dk_SnkhBhMy9s0lO3lBSKt

{
  "title": "Token test 3",
  "author": "Agustin Castro",
  "url": "www.authorization.com",
  "likes": 1,
  "userId": "6668a46ce72e20e17b5d1fcd"
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/6668ab9e5911b9575b1e0fdb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFndUNhc3RybyIsImlkIjoiNjY2OGE0NmNlNzJlMjBlMTdiNWQxZmNkIiwiaWF0IjoxNzE4MTM0ODY2LCJleHAiOjE3MTgxMzg0NjZ9.GAbWISmjkPCVVYz8Y2S21XXQDmi94pmScLqC0DhJug4

### PUT: Update a blog
PUT http://localhost:3001/api/blogs/:id
Content-Type: application/json

{
  "author": "Agustin Castro",
  "likes": 100
}