### Return an error for id not found
GET http://localhost:3001/api/blogs/6658caa96242ac8140ceb2bd

### Return an error for bad format id
GET http://localhost:3001/api/blogs/6658caa96242ac8140ce

### Error when create a blog without title and url
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer :token

{
  "title": "Token test 2",
  "author": "Agustin Castro",
  "url": "www.authorization.com",
  "likes": 1,
  "userId": "6668a46ce72e20e17b5d1fcd"
}

### Error the blog is not exist
DELETE http://localhost:3001/api/blogs/6660fc801f96548785ea85b1

### Bad format to an id blog
DELETE http://localhost:3001/api/blogs/6660fc801f96548785ea85

### Delete a blog without authorization
DELETE http://localhost:3001/api/blogs/6668a39fcf81f1d80a7bf6a5

### Error blog not found
PUT http://localhost:3001/api/blogs/6660fc7c1f96548785ea85b2
Content-Type: application/json

{
  "author": "Agustin Castro",
  "likes": 142
}

### Error bad format id
PUT http://localhost:3001/api/blogs/6660fc7c1f96548785e
Content-Type: application/json

{
  "author": "Agustin Castro",
  "likes": 142
}